"""Added new column to table wind(is_good_for_walk)

Revision ID: 098934ddcbca
Revises: 22343b3f112d
Create Date: 2025-05-14 12:42:21.344688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098934ddcbca'
down_revision: Union[str, None] = '22343b3f112d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind', sa.Column('is_good_for_walk', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wind', 'is_good_for_walk')
    # ### end Alembic commands ###
