"""Added new colunm for wind

Revision ID: 165fea13baf6
Revises: 31086020f551
Create Date: 2025-05-13 18:56:53.305920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165fea13baf6'
down_revision: Union[str, None] = '31086020f551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind', sa.Column('is_good_for_walk', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wind', 'is_good_for_walk')
    # ### end Alembic commands ###
