"""Create tables

Revision ID: 31086020f551
Revises: 
Create Date: 2025-05-13 18:04:36.234637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31086020f551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('air_quality_carbon_monoxide', sa.Float(), nullable=True),
    sa.Column('moon_phase', sa.Enum('New', 'Waxing_Crescent', 'First_Quarter', 'Waxing_Gibbous', 'Full', 'Waning_Gibbous', 'Last_Quarter', 'Waning_Crescent', name='moonphaseenum'), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_degree', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.String(), nullable=True),
    sa.Column('gust_mph', sa.Float(), nullable=True),
    sa.Column('gust_kph', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['weather_id'], ['weather_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weather_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind')
    op.drop_table('weather_record')
    # ### end Alembic commands ###
